  
name: Whatever
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Whatever
        run: |
            git diff ttSettingsDarkMode..master
